"""initial m0 tables

Revision ID: ea917fbdae08
Revises: 
Create Date: 2026-04-17 16:08:41.745284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ea917fbdae08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_file', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('success_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('skipped_records', sa.Integer(), nullable=False),
    sa.Column('unresolved_records', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batch_batch_no'), 'import_batch', ['batch_no'], unique=True)
    op.create_table('meeting_current',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('single_project_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prj_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prj_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ticket_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ticket_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ticket_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_box_talk_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_box_talk_longitude', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_box_talk_latitude', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('re_assessment_risk_level', sa.Integer(), nullable=True),
    sa.Column('current_constr_headcount', sa.Integer(), nullable=True),
    sa.Column('current_construction_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voltage_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('construction_unit_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supervision_unit_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('build_unit_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('leader_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_procedure', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_site_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_constr_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_current_meeting_id'), 'meeting_current', ['meeting_id'], unique=True)
    op.create_index(op.f('ix_meeting_current_single_project_code'), 'meeting_current', ['single_project_code'], unique=False)
    op.create_table('raw_meeting_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('meeting_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('single_project_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('capture_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_meeting_snapshot_import_batch_id'), 'raw_meeting_snapshot', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_raw_meeting_snapshot_meeting_id'), 'raw_meeting_snapshot', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_raw_meeting_snapshot_single_project_code'), 'raw_meeting_snapshot', ['single_project_code'], unique=False)
    op.create_table('raw_tower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('single_project_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tower_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_tower_import_batch_id'), 'raw_tower', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_raw_tower_single_project_code'), 'raw_tower', ['single_project_code'], unique=False)
    op.create_table('raw_year_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('prj_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('single_project_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_year_progress_import_batch_id'), 'raw_year_progress', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_raw_year_progress_prj_code'), 'raw_year_progress', ['prj_code'], unique=False)
    op.create_index(op.f('ix_raw_year_progress_single_project_code'), 'raw_year_progress', ['single_project_code'], unique=False)
    op.create_index(op.f('ix_raw_year_progress_year'), 'raw_year_progress', ['year'], unique=False)
    op.create_table('tower_current',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('single_project_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tower_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tower_sequence_no', sa.Integer(), nullable=True),
    sa.Column('upstream_tower_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('longitude_edit', sa.Float(), nullable=True),
    sa.Column('latitude_edit', sa.Float(), nullable=True),
    sa.Column('bidding_section_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tower_current_single_project_code'), 'tower_current', ['single_project_code'], unique=False)
    op.create_index(op.f('ix_tower_current_tower_no'), 'tower_current', ['tower_no'], unique=False)
    op.create_index(op.f('ix_tower_current_tower_sequence_no'), 'tower_current', ['tower_sequence_no'], unique=False)
    op.create_table('year_progress_current',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prj_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('single_project_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('key_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('single_project_type_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('build_unit_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('build_unit_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_progress', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jhkg_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jhtc_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_year_progress_current_build_unit_name'), 'year_progress_current', ['build_unit_name'], unique=False)
    op.create_index(op.f('ix_year_progress_current_prj_code'), 'year_progress_current', ['prj_code'], unique=False)
    op.create_index(op.f('ix_year_progress_current_single_project_code'), 'year_progress_current', ['single_project_code'], unique=False)
    op.create_index(op.f('ix_year_progress_current_source_code'), 'year_progress_current', ['source_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_year_progress_current_single_project_code'), table_name='year_progress_current')
    op.drop_index(op.f('ix_year_progress_current_prj_code'), table_name='year_progress_current')
    op.drop_index(op.f('ix_year_progress_current_build_unit_name'), table_name='year_progress_current')
    op.drop_table('year_progress_current')
    op.drop_index(op.f('ix_tower_current_tower_sequence_no'), table_name='tower_current')
    op.drop_index(op.f('ix_tower_current_tower_no'), table_name='tower_current')
    op.drop_index(op.f('ix_tower_current_single_project_code'), table_name='tower_current')
    op.drop_table('tower_current')
    op.drop_index(op.f('ix_raw_year_progress_year'), table_name='raw_year_progress')
    op.drop_index(op.f('ix_raw_year_progress_single_project_code'), table_name='raw_year_progress')
    op.drop_index(op.f('ix_raw_year_progress_prj_code'), table_name='raw_year_progress')
    op.drop_index(op.f('ix_raw_year_progress_import_batch_id'), table_name='raw_year_progress')
    op.drop_table('raw_year_progress')
    op.drop_index(op.f('ix_raw_tower_single_project_code'), table_name='raw_tower')
    op.drop_index(op.f('ix_raw_tower_import_batch_id'), table_name='raw_tower')
    op.drop_table('raw_tower')
    op.drop_index(op.f('ix_raw_meeting_snapshot_single_project_code'), table_name='raw_meeting_snapshot')
    op.drop_index(op.f('ix_raw_meeting_snapshot_meeting_id'), table_name='raw_meeting_snapshot')
    op.drop_index(op.f('ix_raw_meeting_snapshot_import_batch_id'), table_name='raw_meeting_snapshot')
    op.drop_table('raw_meeting_snapshot')
    op.drop_index(op.f('ix_meeting_current_single_project_code'), table_name='meeting_current')
    op.drop_index(op.f('ix_meeting_current_meeting_id'), table_name='meeting_current')
    op.drop_table('meeting_current')
    op.drop_index(op.f('ix_import_batch_batch_no'), table_name='import_batch')
    op.drop_table('import_batch')
    # ### end Alembic commands ###
